version: "3.8"

services:
  todo-app:
    image: todo-front-dev
    environment:
      - VITE_BACKEND_URL=/api
    build:
      context: ./todo-frontend 
      dockerfile: Dockerfile 
    container_name: todo-front-dev 
    depends_on:
      - server

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-app 
      - server

  server:
    image: express-app
    depends_on:
      - mongo
      - redis
    build:
      context: ./todo-backend
      dockerfile: ./Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
